version: '3.4'

services:
  ikawari.indexer:
    #image: ${DOCKER_REGISTRY-}ikawariindexer
    #build:
    #  context: .
    #  dockerfile: Ikawari.Indexer/Dockerfile
    container_name: ikawari-indexer
    image: petitpapas/ikawariindexer:1.0.1
    mem_limit: 1024m
    cpus: 0.200

  mongo-database:
    container_name: mongo-db
    image: mongo:5.0.5
    command: "--wiredTigerCacheSizeGB 3"
    mem_limit: 3000m
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - mongo-database:/data/db
      - mongo-database:/data/configdb
    ports:
      - 27017:27017
volumes:
  mongo-database:
    name: mongo-db

